import javax.swing.*;
import java.awt.event.*;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        btnOn.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void disable()
    {   
        btnOn.setEnabled(true);//on button Enable
        btnOff.setEnabled(false);//off button Disable
        txtDisplay.setEnabled(false);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn4.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btnDot.setEnabled(false);
        btnDivision.setEnabled(false);
        btnMultiply.setEnabled(false);
        btnMinus.setEnabled(false);
        btnPlus.setEnabled(false);
        btnEquals.setEnabled(false);
        btnSign.setEnabled(false);
        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
        btn3.setEnabled(false);
        btn0.setEnabled(false);
        btnSin.setEnabled(false);
        btnCos.setEnabled(false);
        btnTan.setEnabled(false);
        btnCot.setEnabled(false);
        btnLog.setEnabled(false);
        btnLn.setEnabled(false);
        btnPower.setEnabled(false);
        btnSqrt.setEnabled(false);
        }  
    public void enable()
    {
        btnOn.setEnabled(false);//on button Disable
        btnOff.setEnabled(true);//off button Enable
        txtDisplay.setEnabled(true);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn4.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btnDot.setEnabled(true);
        btnDivision.setEnabled(true);
        btnMultiply.setEnabled(true);
        btnMinus.setEnabled(true);
        btnPlus.setEnabled(true);
        btnEquals.setEnabled(true);
        btnSign.setEnabled(true);
        btnDelete.setEnabled(true);
        btnClear.setEnabled(true);
        btn3.setEnabled(true);
        btn0.setEnabled(true);
        btnSin.setEnabled(true);
        btnCos.setEnabled(true);
        btnTan.setEnabled(true);
        btnCot.setEnabled(true);
        btnLog.setEnabled(true);
        btnLn.setEnabled(true);
        btnPower.setEnabled(true);
        btnSqrt.setEnabled(true);
        
    }
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlClourss = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btnOn = new javax.swing.JRadioButton();
        btnOff = new javax.swing.JRadioButton();
        btnSin = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnCot = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnSign = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        ComClours = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        pnlClourss.setBackground(new java.awt.Color(204, 204, 204));

        txtDisplay.setFont(new java.awt.Font("Comic Sans MS", 0, 30)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDisplay.setText("0");
        txtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnOn.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(btnOn);
        btnOn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnOn.setText("ON");
        btnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnActionPerformed(evt);
            }
        });

        btnOff.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(btnOff);
        btnOff.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnOff.setText("OFF ");
        btnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffActionPerformed(evt);
            }
        });

        btnSin.setBackground(new java.awt.Color(51, 51, 51));
        btnSin.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnSin.setForeground(new java.awt.Color(255, 255, 255));
        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtunAction(evt);
            }
        });

        btnTan.setBackground(new java.awt.Color(51, 51, 51));
        btnTan.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnTan.setForeground(new java.awt.Color(255, 255, 255));
        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtunAction(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(51, 51, 51));
        btnCos.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnCos.setForeground(new java.awt.Color(255, 255, 255));
        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtunAction(evt);
            }
        });

        btnCot.setBackground(new java.awt.Color(51, 51, 51));
        btnCot.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnCot.setForeground(new java.awt.Color(255, 255, 255));
        btnCot.setText("cot");
        btnCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotButtunAction(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(51, 51, 51));
        btnLog.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });
        btnLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoghandleKeyPressed(evt);
            }
        });

        btnLn.setBackground(new java.awt.Color(51, 51, 51));
        btnLn.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnLn.setForeground(new java.awt.Color(255, 255, 255));
        btnLn.setText("ln");
        btnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });
        btnLn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLnhandleKeyPressed(evt);
            }
        });

        btnPower.setBackground(new java.awt.Color(51, 51, 51));
        btnPower.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        btnPower.setForeground(new java.awt.Color(255, 255, 255));
        btnPower.setText("^");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(51, 51, 51));
        btnSqrt.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        btnSqrt.setForeground(new java.awt.Color(255, 255, 255));
        btnSqrt.setText("√");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(51, 51, 51));
        btnClear.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(51, 51, 51));
        btnDelete.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("←");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        btnDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btn0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnSign.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        btnSign.setText("±");
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });
        btnSign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitButtunAction(evt);
            }
        });
        btnDot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnEquals.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        btnEquals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(51, 51, 51));
        btnPlus.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });
        btnPlus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(51, 51, 51));
        btnMultiply.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnMultiply.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiply.setText("×");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });
        btnMultiply.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnMinus.setBackground(new java.awt.Color(51, 51, 51));
        btnMinus.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus.setText("−");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });
        btnMinus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(51, 51, 51));
        btnDivision.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("÷");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpratorButtunAction(evt);
            }
        });
        btnDivision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleKeyPressed(evt);
            }
        });

        ComClours.setBackground(new java.awt.Color(204, 204, 204));
        ComClours.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ComClours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Dark", "Colored" }));
        ComClours.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComCloursPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout pnlClourssLayout = new javax.swing.GroupLayout(pnlClourss);
        pnlClourss.setLayout(pnlClourssLayout);
        pnlClourssLayout.setHorizontalGroup(
            pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClourssLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClourssLayout.createSequentialGroup()
                        .addComponent(btnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlClourssLayout.createSequentialGroup()
                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlClourssLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlClourssLayout.createSequentialGroup()
                                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSign, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnlClourssLayout.createSequentialGroup()
                                                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnlClourssLayout.createSequentialGroup()
                                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlClourssLayout.createSequentialGroup()
                                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(19, 19, 19)
                                                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pnlClourssLayout.createSequentialGroup()
                                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlClourssLayout.createSequentialGroup()
                                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEquals, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                            .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClourssLayout.createSequentialGroup()
                                    .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlClourssLayout.createSequentialGroup()
                                            .addComponent(btnCot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(95, 95, 95))
                                        .addGroup(pnlClourssLayout.createSequentialGroup()
                                            .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnLn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComClours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlClourssLayout.setVerticalGroup(
            pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClourssLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComClours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlClourssLayout.createSequentialGroup()
                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSin)
                            .addComponent(btnTan)
                            .addComponent(btnLn)
                            .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCos)
                                .addComponent(btnCot)
                                .addComponent(btnLog))
                            .addComponent(btnSqrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClourssLayout.createSequentialGroup()
                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlClourssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSign, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlClourss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlClourss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String state ="operand1";
    String op ="";
    double operand1 =0;
    double operand2 =0;
    double result =0;
    private void DigitButtunAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitButtunAction
         JButton btn = (JButton) evt.getSource();
        
        String str = txtDisplay.getText();
        
        switch(state) {
            case "op":
                str = "";
                state = "operand2";
                break;
            
            case "result":
                str = "";
                state = "operand1";
                break;
        }
        
        if(str.equals("0") && btn!=btnDot) {
            str = "";
        }

        if(btn==btnDot) {
            if(!str.contains(".")) {
                str = str + ".";
            }
        } else {
            str = str + btn.getText();
        }
        
        txtDisplay.setText(str);
    }//GEN-LAST:event_DigitButtunAction
    
    private void OpratorButtunAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpratorButtunAction
         switch(state) {
            case "operand1":
                operand1 = Double.parseDouble(txtDisplay.getText());
                break;
                
            case "operand2":
                btnEqualsActionPerformed(null);
                operand1 = result;
                break;
                
            case "result":
                operand1 = result;
                break;
        }
        
        state = "op";
        
        JButton btn = (JButton) evt.getSource();
        
        if(btn==btnPlus) op = "+";
        if(btn==btnMinus) op = "-";
        if(btn==btnMultiply) op = "*";
        if(btn==btnDivision) op = "/";
        if(btn==btnPower) op = "^";
        if(btn==btnLog) op = "log";
        if(btn==btnSqrt) op = "√";
        if(btn==btnLn) op = "ln";
        
    }//GEN-LAST:event_OpratorButtunAction

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
       switch(state) {
            case "operand1":
                operand1 = Double.parseDouble(txtDisplay.getText());
                result = operand1;
                state = "result";
                return;
                
            case "operand2":
                operand2 = Double.parseDouble(txtDisplay.getText());
                break;
                
            case "op":
                operand2 = operand1;
                break;
                
            case "result":
                operand1 = result;
                break;
        }
        
        switch(op) {
            case "+":
                result = operand1 + operand2;
                break;
            case "-":
                result = operand1 - operand2;
                break;
            case "*":
                result = operand1 * operand2;
                break;
            case "/":
                result = operand1 / operand2;
                break;
            case "^":
                result =Math.pow(operand1, operand2);
                break; 
            case "log":
                result =Math.log10(operand1);
                break;
            case "√":
                result =Math.sqrt(operand1);
                break;
                case "ln":
                result =Math.log(operand1);
                break;
        }
        
        String strResult = String.valueOf(result);
        if(strResult.endsWith(".0")) {
            strResult = strResult.substring(0, strResult.length()-2);
        }
        txtDisplay.setText(strResult);

        state = "result";
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        state = "operand1";
        op = "";
        operand1 = 0;
        operand2 = 0;
        result = 0;
        txtDisplay.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String str = txtDisplay.getText();
        
        str = str.substring(0, str.length()-1);

        if(state.equals("result")) {
            str = "0";
        }
        
        if(str.isEmpty() || str.equals("-")) {
            str = "0";
           }
         txtDisplay.setText(str);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
         String str = txtDisplay.getText();
        
        if(str.startsWith("-")) {
            str = str.substring(1);
        } else {
            if(!str.equals("0")) {
                str = "-" + str;
            }
        }
        
        txtDisplay.setText(str);
    }//GEN-LAST:event_btnSignActionPerformed

    private void handleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_handleKeyPressed
       String KeyText = KeyEvent.getKeyModifiersText(evt.getModifiers())
                + KeyEvent.getKeyText(evt.getKeyCode());
        
        switch(KeyText) {
            case "0":
                btn0.doClick();
                break;
                
            case "1":
                btn1.doClick();
                break;
                
            case "2":
                btn2.doClick();
                break;
                
            case "3":
                btn3.doClick();
                break;
                
            case "4":
                btn4.doClick();
                break;
                
            case "5":
                btn5.doClick();
                break;
                
            case "6":
                btn6.doClick();
                break;
                
            case "7":
                btn7.doClick();
                break;
                
            case "8":
                btn8.doClick();
                break;
                
            case "9":
                btn9.doClick();
                break;
                
            case "Period":
                btnDot.doClick();
                break;
                
            case "ShiftEquals":
                btnPlus.doClick();
                break;
                
            case "Minus":
                btnMinus.doClick();
                break;
                
            case "Shift8":
                btnMultiply.doClick();
                break;
                
            case "Slash":
                btnDivision.doClick();
                break;
                
            case "Escape":
                btnClear.doClick();
                break;
                
            case "Backspace":
            case "Delete":
                btnDelete.doClick();
                break;
                
            case "Space":
                btnEquals.doClick();
                break;
                
            case "CtrlCtrl":
                btnSign.doClick();
                break;
        }
    }//GEN-LAST:event_handleKeyPressed

    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffActionPerformed
       disable();//call disable method
    }//GEN-LAST:event_btnOffActionPerformed

    private void btnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnActionPerformed
        enable();//call enable method
    }//GEN-LAST:event_btnOnActionPerformed

    private void btnLoghandleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoghandleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoghandleKeyPressed

    private void btnLnhandleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLnhandleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLnhandleKeyPressed

    private void sinButtunAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtunAction
         double degrees =Double.parseDouble(txtDisplay.getText());
  
        // convert degrees to radians
        double radians = Math.toRadians(degrees);
  
        // sin() method to get the sine value
        
        double sinValue = Math.sin(radians);
       // prints the sine value
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+sinValue);
        // prints the sine value
       
    }//GEN-LAST:event_sinButtunAction

    private void cosButtunAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtunAction
         double degrees =Double.parseDouble(txtDisplay.getText());
  
        // convert degrees to radians
        double radians = Math.toRadians(degrees);
  
        // cos() method to get the sine value
        
        double cosValue = Math.cos(radians);
       // prints the sine value
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+cosValue);
    }//GEN-LAST:event_cosButtunAction

    private void tanButtunAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtunAction
        double degrees =Double.parseDouble(txtDisplay.getText());
  
        // convert degrees to radians
        double radians = Math.toRadians(degrees);
  
        // tan() method to get the tan value
        
        double tanValue = Math.tan(radians);
       // prints the tan value
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+tanValue);
        
    }//GEN-LAST:event_tanButtunAction

    private void cotButtunAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotButtunAction
         double degrees =Double.parseDouble(txtDisplay.getText());
  
        // convert degrees to radians
        double radians = Math.toRadians(degrees);
  
        // cot() method to get the cot value
        
        double cotValue = 1.0/Math.tan(radians);
       // prints the cot value
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+cotValue);
    }//GEN-LAST:event_cotButtunAction

    private void ComCloursPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComCloursPopupMenuWillBecomeInvisible
        String Clourselected= (String) ComClours.getSelectedItem();
        if(Clourselected=="Dark"){
        pnlClourss.setBackground(Color.BLACK);
        btn0.setBackground(Color.BLACK);
        btnOn.setBackground(Color.BLACK);
        btnOff.setBackground(Color.BLACK);
        txtDisplay.setBackground(Color.BLACK);
        btn1.setBackground(Color.BLACK);
        btn2.setBackground(Color.BLACK);
        btn5.setBackground(Color.BLACK);
        btn6.setBackground(Color.BLACK);
        btn4.setBackground(Color.BLACK);
        btn7.setBackground(Color.BLACK);
        btn8.setBackground(Color.BLACK);
        btn9.setBackground(Color.BLACK);
        btnDot.setBackground(Color.BLACK);
        btnDivision.setBackground(Color.BLACK);
        btnMultiply.setBackground(Color.BLACK);
        btnMinus.setBackground(Color.BLACK);
        btnPlus.setBackground(Color.BLACK);
        btnEquals.setBackground(Color.BLACK);
        btnSign.setBackground(Color.BLACK);
        btnDelete.setBackground(Color.BLACK);
        btnClear.setBackground(Color.BLACK);
        btn3.setBackground(Color.BLACK);
        btn0.setBackground(Color.BLACK);
        btnSin.setBackground(Color.BLACK);
        btnCos.setBackground(Color.BLACK);
        btnTan.setBackground(Color.BLACK);
        btnCot.setBackground(Color.BLACK);
        btnLog.setBackground(Color.BLACK);
        btnLn.setBackground(Color.BLACK);
        btnPower.setBackground(Color.BLACK);
        btnSqrt.setBackground(Color.BLACK);
        txtDisplay.setForeground(Color.WHITE);
        btnSin.setForeground(Color.CYAN);
        btnCos.setForeground(Color.CYAN);
        btnTan.setForeground(Color.CYAN);
        btnCot.setForeground(Color.CYAN);
        btnLn.setForeground(Color.CYAN);
        btnLog.setForeground(Color.CYAN);
        btnSqrt.setForeground(Color.CYAN);
        btnPower.setForeground(Color.CYAN);
        btnDivision.setForeground(Color.CYAN);
        btnMultiply.setForeground(Color.CYAN);
        btnPlus.setForeground(Color.CYAN);
        btnMinus.setForeground(Color.CYAN);
        ComClours.setForeground(Color.CYAN);
        btnDot.setForeground(Color.CYAN);
        btnSign.setForeground(Color.CYAN);
        btnOn.setForeground(Color.CYAN);
        btnOff.setForeground(Color.CYAN);
        btn0.setForeground(Color.WHITE);
        btn1.setForeground(Color.WHITE);
        btn2.setForeground(Color.WHITE);
        btn3.setForeground(Color.WHITE);
        btn4.setForeground(Color.WHITE);
        btn5.setForeground(Color.WHITE);
        btn6.setForeground(Color.WHITE);
        btn7.setForeground(Color.WHITE);
        btn8.setForeground(Color.WHITE);
        btn9.setForeground(Color.WHITE);
        
        
        btnEquals.setForeground(Color.WHITE);
        ComClours.setBackground(Color.BLACK);
        btn1.setBorderPainted(false);
        btn2.setBorderPainted(false);
        btn5.setBorderPainted(false);
        btn6.setBorderPainted(false);
        btn4.setBorderPainted(false);
        btn7.setBorderPainted(false);
        btn8.setBorderPainted(false);
        btn9.setBorderPainted(false);
        btnDot.setBorderPainted(false);
        btnDivision.setBorderPainted(false);
        btnMultiply.setBorderPainted(false);
        btnMinus.setBorderPainted(false);
        btnPlus.setBorderPainted(false);
        btnEquals.setBorderPainted(false);
        btnSign.setBorderPainted(false);
        btnDelete.setBorderPainted(false);
        btnClear.setBorderPainted(false);
        btn3.setBorderPainted(false);
        btn0.setBorderPainted(false);
        btnSin.setBorderPainted(false);
        btnCos.setBorderPainted(false);
        btnTan.setBorderPainted(false);
        btnCot.setBorderPainted(false);
        btnLog.setBorderPainted(false);
        btnLn.setBorderPainted(false);
        btnPower.setBorderPainted(false);
        btnSqrt.setBorderPainted(false);
        
        }
        else if("Simple".equals(Clourselected)){
        ComClours.setBackground(new java.awt.Color(204,204,204));
        pnlClourss.setBackground(new java.awt.Color(204,204,204));
        btn0.setBackground(Color.WHITE);
        btnOn.setBackground(new java.awt.Color(204,204,204));
        btnOff.setBackground(new java.awt.Color(204,204,204));
        txtDisplay.setBackground(Color.WHITE);
        btn1.setBackground(Color.WHITE);
        btn2.setBackground(Color.WHITE);
        btn5.setBackground(Color.WHITE);
        btn6.setBackground(Color.WHITE);
        btn4.setBackground(Color.WHITE);
        btn7.setBackground(Color.WHITE);
        btn8.setBackground(Color.WHITE);
        btn9.setBackground(Color.WHITE);
        btnDot.setBackground(Color.WHITE);
        btnDivision.setBackground(new java.awt.Color(51,51,51));
        btnMultiply.setBackground(new java.awt.Color(51,51,51));
        btnMinus.setBackground(new java.awt.Color(51,51,51));
        btnPlus.setBackground(new java.awt.Color(51,51,51));
        btnEquals.setBackground(Color.WHITE);
        btnSign.setBackground(Color.WHITE);
        btnDelete.setBackground(new java.awt.Color(51,51,51));
        btnClear.setBackground(new java.awt.Color(51,51,51));
        btn3.setBackground(Color.WHITE);
        btn0.setBackground(Color.WHITE);
        btnSin.setBackground(new java.awt.Color(51,51,51));
        btnCos.setBackground(new java.awt.Color(51,51,51));
        btnTan.setBackground(new java.awt.Color(51,51,51));
        btnCot.setBackground(new java.awt.Color(51,51,51));
        btnLog.setBackground(new java.awt.Color(51,51,51));
        btnLn.setBackground(new java.awt.Color(51,51,51));
        btnPower.setBackground(new java.awt.Color(51,51,51));
        btnSqrt.setBackground(new java.awt.Color(51,51,51));
        txtDisplay.setForeground(Color.WHITE);
        btnSin.setForeground(Color.WHITE);
        btnCos.setForeground(Color.WHITE);
        btnTan.setForeground(Color.WHITE);
        btnCot.setForeground(Color.WHITE);
        btnLn.setForeground(Color.WHITE);
        btnLog.setForeground(Color.WHITE);
        btnSqrt.setForeground(Color.WHITE);
        btnPower.setForeground(Color.WHITE);
        btnDivision.setForeground(Color.WHITE);
        btnMultiply.setForeground(Color.WHITE);
        btnPlus.setForeground(Color.WHITE);
        btnMinus.setForeground(Color.WHITE);
        ComClours.setForeground(Color.BLACK);
        btnEquals.setForeground(Color.BLACK);
        btnDot.setForeground(Color.BLACK);
        btnSign.setForeground(Color.BLACK);
        btnOn.setForeground(Color.BLACK);
        btnOff.setForeground(Color.BLACK);
        btn0.setForeground(Color.BLACK);
        btn1.setForeground(Color.BLACK);
        btn2.setForeground(Color.BLACK);
        btn3.setForeground(Color.BLACK);
        btn4.setForeground(Color.BLACK);
        btn5.setForeground(Color.BLACK);
        btn6.setForeground(Color.BLACK);
        btn7.setForeground(Color.BLACK);
        btn8.setForeground(Color.BLACK);
        btn9.setForeground(Color.BLACK);
        
        txtDisplay.setBackground(Color.WHITE);
        txtDisplay.setForeground(Color.BLACK);
        
        
        
        }
        else if("Colored".equals(Clourselected)){
        ComClours.setBackground(new java.awt.Color(255,204,204));
        ComClours.setForeground(Color.MAGENTA);
        pnlClourss.setBackground(new java.awt.Color(255,204,204));
        btn0.setBackground(Color.WHITE);
        btnOn.setBackground(new java.awt.Color(255,204,204));
        btnOff.setBackground(new java.awt.Color(255,204,204));
        txtDisplay.setBackground(new java.awt.Color(255,204,255));
        btn1.setBackground(Color.WHITE);
        btn2.setBackground(Color.WHITE);
        btn5.setBackground(Color.WHITE);
        btn6.setBackground(Color.WHITE);
        btn4.setBackground(Color.WHITE);
        btn7.setBackground(Color.WHITE);
        btn8.setBackground(Color.WHITE);
        btn9.setBackground(Color.WHITE);
        btnDot.setBackground(Color.WHITE);
        btnDivision.setBackground(new java.awt.Color(255,153,102));
        btnMultiply.setBackground(new java.awt.Color(204,204,0));
        btnMinus.setBackground(new java.awt.Color(204,204,255));
        btnPlus.setBackground(new java.awt.Color(255,204,255));
        btnEquals.setBackground(Color.WHITE);
        btnSign.setBackground(Color.WHITE);
        btnDelete.setBackground(new java.awt.Color(0,153,153));
        btnClear.setBackground(new java.awt.Color(0,153,0));
        btn3.setBackground(Color.WHITE);
        btn0.setBackground(Color.WHITE);
        btnSin.setBackground(Color.cyan);
        btnCos.setBackground(Color.GREEN);
        btnTan.setBackground(Color.ORANGE);
        btnCot.setBackground(Color.MAGENTA);
        btnLog.setBackground(Color.blue);
        btnLn.setBackground(Color.RED);
        btnPower.setBackground(new java.awt.Color(204,51,255));
        btnSqrt.setBackground(new java.awt.Color(153,153,0));
        txtDisplay.setForeground(Color.WHITE);
        btnSin.setForeground(Color.WHITE);
        btnCos.setForeground(Color.WHITE);
        btnTan.setForeground(Color.WHITE);
        btnCot.setForeground(Color.WHITE);
        btnLn.setForeground(Color.WHITE);
        btnLog.setForeground(Color.WHITE);
        btnSqrt.setForeground(Color.WHITE);
        btnPower.setForeground(Color.WHITE);
        btnDivision.setForeground(Color.WHITE);
        btnMultiply.setForeground(Color.WHITE);
        btnPlus.setForeground(Color.WHITE);
        btnMinus.setForeground(Color.WHITE);
        ComClours.setForeground(Color.BLACK);
        btnEquals.setForeground(Color.BLACK);
        btnDot.setForeground(Color.BLACK);
        btnSign.setForeground(Color.BLACK);
        btnOn.setForeground(Color.BLACK);
        btnOff.setForeground(Color.BLACK);
        btn0.setForeground(new java.awt.Color(0,204,0));
        btn1.setForeground(new java.awt.Color(255,0,255));
        btn2.setForeground(new java.awt.Color(255,51,51));
        btn3.setForeground(new java.awt.Color(204,0,255));
        btn4.setForeground(new java.awt.Color(153,0,0));
        btn5.setForeground(new java.awt.Color(102,102,255));
        btn6.setForeground(new java.awt.Color(255,153,0));
        btn7.setForeground(new java.awt.Color(251,0,204));
        btn8.setForeground(new java.awt.Color(204,0,0));
        btn9.setForeground(Color.CYAN);
        
        txtDisplay.setBackground(new java.awt.Color(255,255,204));
        txtDisplay.setForeground(Color.BLACK);
        
        
        
        }
    }//GEN-LAST:event_ComCloursPopupMenuWillBecomeInvisible
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComClours;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCot;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JRadioButton btnOff;
    private javax.swing.JRadioButton btnOn;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnSign;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnTan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel pnlClourss;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
